### ISSUE TITLE
Transaction flow - "Broadcasting" message while in Pending state

### ISSUE THREAD

**Issue by ronnno** [orbs-network/staking-wallet#100]
When each transaction is sent there are three steps:

1. broadcasting (the cycling is displayed)
2. Pending
3. Confirmed (waiting for confirmation count increase)

In some cases (when delegating for the first time via the Stake dialog) PENDING is shown after a transaction is committed, for at least one more confirmation.

In other cases - no Pending: we wait in step No1 until confirmation is recieved, then we jump directly to No3, skipping No2

The flow should be consistent -

**Comment by ronnno** [comment]
duplicates #78

**Comment by ronnno** [comment]
best to test on ropsten to see the delays

**Comment by denis-mixin** [comment]
https://github.com/orbs-network/staking-wallet/pull/132

**Comment by denis-mixin** [comment]
done and merged to dev branch
