### ISSUE TITLE
update Korean translation

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#102]
Please update the latest Korean translation.
There are some critical errors (for example, cooldown period)

Translation is updated thru https://www.locize.app/

**Comment by ronnno** [comment]
Hi, does the account in locize already reflect the requested fixes? or do we need to translate? Also, can you indicate which entries changed and if any were added?
@Eddy-orbs

**Comment by Eddy-orbs** [comment]
@ronnno 

I think it is not reflected yet.
![image](https://user-images.githubusercontent.com/56513320/119338781-642d3780-bccb-11eb-840e-fea1aecc2c41.png)


changed item are:
"unstakingSubStep_warning_thereAreOrbsInCooldownBody (unstakingWizard)"
"cannotUnstakeWhenThereAreOrbsReadyToWithdraw (alerts)"

PS.
I cannot check thru product because I can see them only when some token is cooling down.

**Comment by denis-mixin** [comment]
updated

**Comment by ronnno** [comment]
is this fixed in #151 ?

**Comment by denis-mixin** [comment]
I ran the sync translations script.

https://github.com/orbs-network/staking-wallet/pull/152
