### ISSUE TITLE
Add "copy address" icon for Guardian address 

### ISSUE THREAD

**Issue by ronnno** [orbs-network/staking-wallet#107]
Allow one click copying of the Guardian address.

Preferably, the copied address should be checksum capitalized. 

Copy icon should not be too obtrusive. wait for Graphical design

**Comment by ronnno** [comment]
<img width="270" alt="Screen Shot 2021-05-24 at 15 42 58" src="https://user-images.githubusercontent.com/15799888/119354762-1efa0d00-bcad-11eb-9352-dd66d1bb6020.png">
<img width="1305" alt="Screen Shot 2021-05-24 at 15 42 28" src="https://user-images.githubusercontent.com/15799888/119354844-3507cd80-bcad-11eb-9b8c-0d57aecf0b9a.png">

**Comment by denis-mixin** [comment]
https://github.com/orbs-network/staking-wallet/pull/119

**Comment by ronnno** [comment]
Please send to Marina for design confirmation

**Comment by ronnno** [comment]
@denis-mixin

**Comment by denis-mixin** [comment]
done and merged to dev branch
