### ISSUE TITLE
Formatting of decimals

### ISSUE THREAD

**Issue by ronnno** [orbs-network/staking-wallet#120]
- When staking a non-rounded amount - we don't indicate that the amount is not round in the staking dialog:
![Screen Shot 2021-05-24 at 16 14 43](https://user-images.githubusercontent.com/15799888/119353338-6d0e1100-bcab-11eb-971b-336a532c44cb.png)
this was taken after approving 1.000000000001
- cannot type 0. in the text box.
- top row boxes don't show decimals or indication for non round number
- max button does not include fractions

**Comment by denis-mixin** [comment]
pull request created for this issue
