### ISSUE TITLE
Warn when not on Mainnet

### ISSUE THREAD

**Issue by ronnno** [orbs-network/staking-wallet#153]
When user is setting Metamask to run with testnet or local ethereum Tetra fails without proper error. At the same time we should allow users to test against Ropsten

EDIT:

add to env files:
TARGET_NETWORK param that'll hold the targeted network identifier (default: 1)

if the connected network != TARGET_NETWORK => add a modal message (disallow any progress without resolving the network issue) stating that you are on the wrong message: 
"Wrong network. "
"Please connect to the appropriate Ethereum network."
icon :  put a disconnected icon below the message 

* for DEV env, disable the modal message.

**Comment by denis-mixin** [comment]
pr:  #155 
waiting for design from marina
