### ISSUE TITLE
"Select Guardian" should be step 1 not 3rd in staking wizard

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#16]
# Problem:
- found some cases that got "approve", "stake" without completing step 3 (delegation).
- Cannot select guardian at the front page

# Steps to reproduce
1. Close Tetra windows before finish step 3 (select guardian)
2. Re-login Tetra

You can see all balance is already staked. And there is no way to select guardian again.

# Reason
caused by long confirmation time with low fee setting, closing browser, computer power off accidentally, etc.

* guide to Hedron or sending 0.07 is workaround, not a solution.

# Suggestion to resolve
- Move "Select Guardian" to the first step. It will prevent many unexpected cases.
- implement "Select Guardian" feature at the front page (currently, only CHANGING guardian is possible)
- show warning message when user is staking without delegating.

![issue_tetra_cannot_select_guardian](https://user-images.githubusercontent.com/56513320/79045012-c94ad880-7c43-11ea-9d38-6fb91033919b.png)
Cannot select guardian here.

**Comment by Eddy-orbs** [comment]
![image](https://user-images.githubusercontent.com/56513320/79630507-cf354200-818c-11ea-8035-add969b3cb87.png)

Another case is reported.

**Comment by Eddy-orbs** [comment]
Here is one more user case occured.
https://orbs-network.github.io/voting/ko/reward?address=0x0004f536eb5212391f236b83e298f608063cc593

**Comment by talkol** [comment]
We decided that we're not changing the order of the steps. What we're doing is moving "My Guardian" to its own separate section in the home screen. And we're adding warning there if no guardian is selected and adding ability to change guardian straight from there. These changes should resolve this issue.

**Comment by Eddy-orbs** [comment]
Additional warning will enough on current stage.
I'll close issue.
Will upload if any further request income later.
