### ISSUE TITLE
Add FAQ

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#17]
# Problem:
Too many simple questions repeated.

# Steps to reproduce:

# Reason:
- Some try without understanding the full process. Some people even do not know about "gas fee".
- Don't know how to transit wallet to Metamask from other wallets.
- iPhone users asking.

# Suggestion to resolve
FAQ / Guide content should be embedded or linked in Tetra.
if we integrate all those info into Tetra, it is easy to recognize.

**Comment by talkol** [comment]
Warning message if the ETH balance is low/zero to explain the fee thing
