### ISSUE TITLE
Check user input before execute transaction

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#18]
# Problem:
Cause wasting gas fee.
User complaints (I already had). Unkind UX.

# Steps to reproduce:
1. Click "Stake your ORBS" button
2. Input more than available balance.
3. proceed step 1 as is.
4. transaction in step 2 gives error.

ps) no way to cancel wizard or exit. User must reload browser which is not guided.

# Reason:
- Technically, "Approve" amount can be more than balance.
- Tetra take "Stake" amount same as approved.

# Suggestion to resolve:
Check user input amount and disable proceed when it's more than have.

**Comment by talkol** [comment]
Edge conditions to check: 
1. Stake more than balance
2. Zero

**Comment by OrLavy** [comment]
Fixed in #42

**Comment by Eddy-orbs** [comment]
Verified.
