### ISSUE TITLE
Tetra fails to detect selected guardian

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#19]
![issue_tetra_transfer_guardian_selection](https://user-images.githubusercontent.com/56513320/79045516-82aaad80-7c46-11ea-921f-11a7389f7c8f.png)
![issue_tetra_transfer_guardian_selection2](https://user-images.githubusercontent.com/56513320/79045517-83dbda80-7c46-11ea-9e26-da289befe75a.png)

# Problem:
User duplicate delegation process spending extra gas fee.

# Steps to reproduce:
Preaction) Delegate to any guardian by sending 0.07 ORBS
### Case A
1. Login TETRA
2. Stake your ORBS
3. In Step 3, see button at selected guardian row
### Case B
1. Login TETRA
2. See Guardian's list below. see selected guardian is NOT selected

# Reason:
Tetra detects user is delegated with 0.07 transfer method.
But Tetra does not detects user previously delegated to "which" guardian.

# Suggestion to resolve:

- Detect selected guardian and disply proper UI.
- Should show button "KEEP" or checked circle for previously selected guardian

**Comment by OrLavy** [comment]
Resolved with #26

**Comment by Eddy-orbs** [comment]
Verified
