### ISSUE TITLE
Add more info about Guardian

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#21]
# REQUIREMENT:
add more info about guardians which delegators can refer to select guardian.

# SUGGESTION:
* put more columns or show popup when guardian row is clicked.

------

below image shows some guardian's info at mobile app.
Tetra also need to show more info about guardians to help delegator selecting their guardian.
Currently, columns in Tetra are not well organized.
For example, 
"Voted for next elections" is only in Hedron.
"Voted in previous election" is only in Tetra.

People also want to see how much tokens guardian is holding in their account easily.
Tetra is easily able to support this programmatically.

------

![image](https://user-images.githubusercontent.com/56513320/79417323-b130db80-7fec-11ea-95ef-b73ac62fb36b.png)

**Comment by talkol** [comment]
A detail button is a good idea
