### ISSUE TITLE
Cannot Restake when cooldown is finished

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#22]
## Issue:
To Restake unstaked tokens after cooldown period, user have to withdraw and proceed stake wizard again.
Restake function is technically available but TETRA UX hide the button.

## Problem:
User spends more gas fee (Withdraw, Approve, Stake) which can make it once (Restake).

## Solution:
Do not hide "Restake" button when cooldown is done.

**Comment by talkol** [comment]
Let's add the restake button

**Comment by Eddy-orbs** [comment]
re-wrote new issue. Close this.
