### ISSUE TITLE
Rewards info in Tetra

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#23]
* This issue is raise from community users.

## Issue:
* Uncomfortable to track user's pos information.
Community request implementation as we presented. (please see image)
![image](https://user-images.githubusercontent.com/56513320/79552699-54a9eb00-80d6-11ea-84d8-185a195db261.png)

ie. To check next election schedule, need 3 more clicks:
Click link to rewards page > Click Delegator menu > Click block number

## Solution:
Implement it as presented.

please refer how mobile app is working (https://play.google.com/store/apps/details?id=com.orbs.pos)

**Comment by Eddy-orbs** [comment]
Total distributed reward, Total accumulated rewards are updated. Nice.

**Comment by talkol** [comment]
The only missing part is the elections count down and this part is not relevant for V2 (since continuous elections) so let's close. I don't want to implement only for V1
