### ISSUE TITLE
Input number

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#31]
![image](https://user-images.githubusercontent.com/56513320/80439573-cdfcd580-8941-11ea-86c5-b9e8778a3868.png)

The first digit is always "ZERO" unnecessarily.
When erase zero and type other number, tetra return it to zero again.

**Comment by OrLavy** [comment]
Fixed in #42

**Comment by Eddy-orbs** [comment]
Verified
