### ISSUE TITLE
Separate section for "my guardian"

### ISSUE THREAD

**Issue by talkol** [orbs-network/staking-wallet#34]
Separate section for "My Guardian".

The new section should appear before "All Guardians", and then remove the highlight of my guardian from the "All Guardians" list.

In this sections include:

1. Button to change guardian
2. If no guardian is selected, a warning that one must be selected to get rewards
3. In V2, if the guardian is not performing well enough and I'm not getting rewards, a warning to indicate this. We want stakers to switch guardian if needed

**Comment by OrLavy** [comment]
Added in #42
