### ISSUE TITLE
[Mobile] Cannot scroll "Select Guardian" in staking wizard

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#40]
### type
- [x] bug

### Environments
- [x] Mobile

Cannot scroll down to page indicator.
Only the first five guardians are available to select unless search name.

![image](https://user-images.githubusercontent.com/56513320/80768206-b7928c00-8b84-11ea-9574-8c8f678b067a.png)

**Comment by OrLavy** [comment]
Fixed with #43
