### ISSUE TITLE
position of "Select" button

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#41]
### type
- [x] enhancement

### Environments
- [x] Mobile
- [x] Desktop

I recommend "SELECT" button come to the first column to find out how to select easily.
(remove additional user action of horizontal scroll)

## AS-IS
![image](https://user-images.githubusercontent.com/56513320/80768435-5e772800-8b85-11ea-9f19-389f0400efc6.png)

## TO-BE
![image](https://user-images.githubusercontent.com/56513320/80768425-57e8b080-8b85-11ea-9a74-ba3b78731c1f.png)

**Comment by talkol** [comment]
Also we can make the button a little smaller and reduce the padding
