### ISSUE TITLE
Tetra shows ZERO rewards

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#47]
Tetra shows ZERO rewards by loading failed.

address: 0x2107b9EbafE8Bcd830c40991aBA35ab79811Ca25

![image](https://user-images.githubusercontent.com/56513320/84120330-a2a4f480-aa70-11ea-8b88-4bbe3b4c0342.png)

You can see his rewards should not be ZERO:

https://orbs-network.github.io/voting/reward?address=0x2107b9EbafE8Bcd830c40991aBA35ab79811Ca25

**Comment by OrLavy** [comment]
After talking with the user, it was a local network problem.
