### ISSUE TITLE
Skip allowance step if already completed

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#48]
There are several complaints regarding staking wizard failure.

[ problem ]
Recently, ether network is unstable. So staking is failed(or timeout or user retrial after long waiting) due to gas fee issue.
This causes a lot of wasting users' eth and complaining Tetra.

[ AS-IS ]
step1. let user approve amount > waiting network confirmation > move to step2.

[ TO-BE ]
step1. check allowance is == 0. 
If zero, let user proceed approval as-is.
If > 0, skip step1 and move to step2. (or add skip button let user skip when he/she wants)

This will prevent duplication of "approve" process which can save user's gas fee.
(ORBS PoS wallet mobile app is already implemented like this and had good feedback)

**Comment by OdedWx** [comment]
Nice improvement, check (allowance >= amount) in case there is a partial allowance (unlikely, but a user may change the amount).

**Comment by OrLavy** [comment]
Fixed with #49

**Comment by Eddy-orbs** [comment]
Tested and confirmed. 

I noticed this and Community is very happy with this fix.

Nice work, Or.
Thanks.
