### ISSUE TITLE
Tetra with Coinbase wallet (iOS mobile)

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#83]
Tetra does not shows address when entered via Coinbase Wallet's dapp broswer (iOS)

**Comment by Eddy-orbs** [comment]
screen shot.

* No address, No Guardian info displayed @ conbase wallet

![image](https://user-images.githubusercontent.com/56513320/113727396-0f8c2800-9730-11eb-9be4-9ff987c0ea9d.png)

**Comment by ronnno** [comment]
resolved in #109
