### ISSUE TITLE
Support "NODE_ENV=production"

### ISSUE THREAD

**Issue by ronnno** [orbs-network/staking-wallet#85]
currently we override NODE_ENV to be "development" always - as a workaround to solve some issues - even when its set initially to "production" or other.. 

1. never override the value of NODE_ENV in the code
2. resolve issues when it's not "development"

**Comment by ronnno** [comment]
low prioirty

**Comment by Eddy-orbs** [comment]
How can I verify(or test) this with Tetra website?

**Comment by ronnno** [comment]
you cannot, this is non functional. 

there are changes in how the website is packed / loaded. this should effect network load and speed of loading tetra
