### ISSUE TITLE
CSS adjustments for Korean and Japanese

### ISSUE THREAD

**Issue by ronnno** [orbs-network/staking-wallet#87]
Eddy writes:
I'd like to suggest minor fix (it's about outfit)
As you see word-wrap gives bad looks. It can be fixed with putting "word-break" css property as "keep-all" in script. "normal" is default which is only working with English and breaks with Korean and Japanese. "keep-all" makes all happy.

![image](https://user-images.githubusercontent.com/15799888/113739690-b2c94700-9708-11eb-9d7b-d75fe649d3ad.png)

reference: http://www.w3big.com/cssref/css3-pr-word-break.html

**Comment by Eddy-orbs** [comment]
Testnet Looks good. Let's apply this in main product.
