### ISSUE TITLE
position of guardian "Select" button

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#88]
### type
- [x] enhancement

### Environments
- [x] Mobile
- [x] Desktop

I recommend "SELECT" button come to the first column to find out how to select easily.
(remove additional user action of horizontal scroll)

## AS-IS
![image](https://user-images.githubusercontent.com/56513320/80768435-5e772800-8b85-11ea-9f19-389f0400efc6.png)

## TO-BE
![image](https://user-images.githubusercontent.com/56513320/80768425-57e8b080-8b85-11ea-9a74-ba3b78731c1f.png)

**Comment by Eddy-orbs** [comment]
TAL: Good idea - let's move the button to be first

https://github.com/orbs-network/staking-wallet/issues/41

**Comment by ronnno** [comment]
Lets do this for browsers. 

Regardless, in mobile the design changes in #94. So for mobile consider making the entire box selectable.

**Comment by denis-mixin** [comment]
this will be in the same pr as the #94, because it is the same component
