### ISSUE TITLE
put "Restake" button with "Withdraw" button when cooldown is finished

### ISSUE THREAD

**Issue by Eddy-orbs** [orbs-network/staking-wallet#90]
## Issue:
To Restake unstaked tokens after cooldown period, user have to withdraw and proceed stake wizard again.
Restake function is technically available but TETRA UX hide the button.

## Problem:
User spends more gas fee (Withdraw, Approve, Stake) which can make it once (Restake).

## Solution:
Do not hide "Restake" button when cooldown is done.

**Comment by denis-mixin** [comment]
created pr
https://github.com/orbs-network/staking-wallet/pull/131

**Comment by denis-mixin** [comment]
done and merged to dev

**Comment by denis-mixin** [comment]
withdraw - change btn text

**Comment by denis6421** [comment]
changed the Withdraw button text from Withdraw your tokens to Withdraw.
